<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Jm1ProductionsBp09.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>jm1-productions-bp09-reviewer-plugin</PackageId>
    <Version>$(FileVersion)</Version>
    <Authors>J Merrill One</Authors>
    <Company>J Merrill One</Company>
    <Description>Bounded Productions BP-09 reviewer action.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.60" PrivateAssets="All" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>

</Project>
